name: Build and tests on pull request - EssentialFrame

on:
  push:
    branches: [ 'stage*',dev,main ]

jobs:
  build-and-push-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ "7.0.x" ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/piotrkantorowicz/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.ACTION_GITHUB_TOKEN}}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Tests
        run: dotnet tests --logger "trx;LogFilePrefix=Tests.trx" --results-directory "TestResults-$DOTNET_VERSION"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults-${{ env.DOTNET_VERSION }}
          path: TestResults-${{ env.DOTNET_VERSION }}
        if: ${{ always() }}

      - name: Tests report generation
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: TestResults-${{ env.DOTNET_VERSION}}
          path: '**/*.trx'
          reporter: dotnet-trx
          list-tests: 'failed'